=begin
https://projecteuler.net/problem=2

Even Fibonacci numbers

Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
=end

# Things to change for every new problem: number in class name on first and last lines

require_relative 'euler_math'

class Problem002
  FIB1 = 1
  FIB2 = 2
  MAX = 4_000_000
  
  def do_problem
    sum = 0
    
    current_lower = FIB1
    current_higher = FIB2

    while current_higher < MAX do
      if EulerMath.isEven? current_higher
        sum += current_higher
      end
      
      next_fib = current_higher + current_lower
      current_lower = current_higher
      current_higher = next_fib
    end

    sum
  end
end

puts problem = Problem002.new.do_problem()